version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.3

workflows:
  build-test:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci

      - node/test:
          requires:
            - "node/run"
          filters:
            branches:
              only:
                - circleci

      - heroku/deploy-via-git:
          requires:
            - "node/run"
            - "node/test"
          app-name: "heroku-circle-ci-5iw4"
          filters:
            branches:
              only:
                - circleci

      - docker/publish:
          requires:
            - "node/run"
            - "node/test"
          image: eliwena/joke-app:latest
          docker-username: eliwena
          filters:
            branches:
              only:
                - circleci
          